lexik_jwt_authentication:
    public_key_path: "%kernel.project_dir%/config/jwt/public.pem"
    private_key_path: "%kernel.project_dir%/config/jwt/private.pem"
    pass_phrase: '%env(JWT_PASSPHRASE)%'